services:
  ouroboros-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ouroboros-server
    ports:
      - '8000:8000'
    volumes:
      - ouroboros-volume:/volume
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OUR_ENV=docker
volumes:
  ouroboros-volume:
    name: ouroboros-volume